1. Write a Python Program to Add Two Matrices?

In [5]:
import pandas as pd
from numpy.random import randn
import numpy as np
m1=np.matrix(np.random.randn(2,2))
print(m1)
m2=np.matrix(np.random.randn(2,2))
print(m2)
print(m1+m2)

[[-0.46444434  1.24786293]
 [ 0.75324745  1.64478776]]
[[-0.54418964  1.68909693]
 [ 1.07399497 -2.26358174]]
[[-1.00863398  2.93695986]
 [ 1.82724241 -0.61879398]]


2. Write a Python Program to Multiply Two Matrices?

In [7]:
import pandas as pd
from numpy.random import randn
import numpy as np
m1=np.matrix(np.random.randn(2,2))
print(m1)
m2=np.matrix(np.random.randn(2,2))
print(m2)
print()
print(m1@m2)

[[ 0.06427348  1.72925441]
 [ 0.7146548  -0.81677078]]
[[ 1.38548692 -0.47078559]
 [ 0.06041001  1.27349696]]

[[ 0.19351435  2.17194121]
 [ 0.94080375 -1.37660429]]


3. Write a Python Program to Transpose a Matrix?

In [10]:
import pandas as pd
import numpy as np
m1=np.matrix([[1,2,3],[5,6,7],[7,8,9],[5,4,6]])
print(m1.shape)
m1=m1.T
print(m1.shape)

(4, 3)
(3, 4)


4. Write a Python Program to Sort Words in Alphabetic Order?

In [13]:
s= input()
l=s.split()
l.sort()
print(l)

ram rose aman nav rishab raman neera
['aman', 'nav', 'neera', 'ram', 'raman', 'rishab', 'rose']


5. Write a Python Program to Remove Punctuation From a String?

In [23]:
s=input()
res=''
l1=['{', '}', '|', '~', '[',']','/','^','_','`',':',';','>','<','=','?','@','#','$','%','&','*','(',')','-','.',',','!']
l=list(s)
for i in l:
    if(i in l1):
        l.remove(i)
res=''.join(l)
print(res)

%myname@naveen<kumar
mynamenaveenkumar
